services:
  postgres:
    image: postgres:15.3-alpine
    container_name: yatube-pg
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1488
      POSTGRES_DB: yatube_db
    volumes:
      - ./yatube_db-dump.sql:/docker-entrypoint-initdb.d/initial.sql
      - yatube-pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postgres

  pgadmin:
    depends_on:
      - postgres
    image: dpage/pgadmin4:7.3
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@yatube.com"
      PGADMIN_DEFAULT_PASSWORD: "1488"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - yatube-pgadmin-data:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - postgres

volumes:
  yatube-pg-data:
  yatube-pgadmin-data:

networks:
  postgres:
    driver: bridge
